// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessagePackage.proto

package com.pandong.tool.gateway.common.model;

public final class GatewayProto {
  private GatewayProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code netty.OperationType}
   */
  public enum OperationType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>HEARTBEAT = 0;</code>
     */
    HEARTBEAT(0),
    /**
     * <code>REGISTER = 1;</code>
     */
    REGISTER(1),
    ;

    /**
     * <code>HEARTBEAT = 0;</code>
     */
    public static final int HEARTBEAT_VALUE = 0;
    /**
     * <code>REGISTER = 1;</code>
     */
    public static final int REGISTER_VALUE = 1;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static OperationType valueOf(int value) {
      return forNumber(value);
    }

    public static OperationType forNumber(int value) {
      switch (value) {
        case 0: return HEARTBEAT;
        case 1: return REGISTER;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<OperationType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        OperationType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<OperationType>() {
            public OperationType findValueByNumber(int number) {
              return OperationType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return GatewayProto.getDescriptor().getEnumTypes().get(0);
    }

    private static final OperationType[] VALUES = values();

    public static OperationType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private OperationType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:netty.OperationType)
  }

  public interface TransferOrBuilder extends
      // @@protoc_insertion_point(interface_extends:netty.Transfer)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int64 request_id = 1 [default = 0];</code>
     */
    boolean hasRequestId();
    /**
     * <code>optional int64 request_id = 1 [default = 0];</code>
     */
    long getRequestId();

    /**
     * <code>required int64 node_id = 2;</code>
     */
    boolean hasNodeId();
    /**
     * <code>required int64 node_id = 2;</code>
     */
    long getNodeId();

    /**
     * <code>required string node_host = 3;</code>
     */
    boolean hasNodeHost();
    /**
     * <code>required string node_host = 3;</code>
     */
    String getNodeHost();
    /**
     * <code>required string node_host = 3;</code>
     */
    com.google.protobuf.ByteString
        getNodeHostBytes();

    /**
     * <code>required int32 node_port = 4;</code>
     */
    boolean hasNodePort();
    /**
     * <code>required int32 node_port = 4;</code>
     */
    int getNodePort();

    /**
     * <code>optional string service_name = 5;</code>
     */
    boolean hasServiceName();
    /**
     * <code>optional string service_name = 5;</code>
     */
    String getServiceName();
    /**
     * <code>optional string service_name = 5;</code>
     */
    com.google.protobuf.ByteString
        getServiceNameBytes();

    /**
     * <code>optional string service_host = 6;</code>
     */
    boolean hasServiceHost();
    /**
     * <code>optional string service_host = 6;</code>
     */
    String getServiceHost();
    /**
     * <code>optional string service_host = 6;</code>
     */
    com.google.protobuf.ByteString
        getServiceHostBytes();

    /**
     * <code>optional int64 service_id = 7;</code>
     */
    boolean hasServiceId();
    /**
     * <code>optional int64 service_id = 7;</code>
     */
    long getServiceId();

    /**
     * <code>required .netty.OperationType operation = 8;</code>
     */
    boolean hasOperation();
    /**
     * <code>required .netty.OperationType operation = 8;</code>
     */
    OperationType getOperation();

    /**
     * <code>optional string signature = 9;</code>
     */
    boolean hasSignature();
    /**
     * <code>optional string signature = 9;</code>
     */
    String getSignature();
    /**
     * <code>optional string signature = 9;</code>
     */
    com.google.protobuf.ByteString
        getSignatureBytes();

    /**
     * <code>optional bytes data = 10;</code>
     */
    boolean hasData();
    /**
     * <code>optional bytes data = 10;</code>
     */
    com.google.protobuf.ByteString getData();
  }
  /**
   * Protobuf type {@code netty.Transfer}
   */
  public  static final class Transfer extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:netty.Transfer)
      TransferOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Transfer.newBuilder() to construct.
    private Transfer(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Transfer() {
      requestId_ = 0L;
      nodeId_ = 0L;
      nodeHost_ = "";
      nodePort_ = 0;
      serviceName_ = "";
      serviceHost_ = "";
      serviceId_ = 0L;
      operation_ = 0;
      signature_ = "";
      data_ = com.google.protobuf.ByteString.EMPTY;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Transfer(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              requestId_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              nodeId_ = input.readInt64();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              nodeHost_ = bs;
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              nodePort_ = input.readInt32();
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              serviceName_ = bs;
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              serviceHost_ = bs;
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              serviceId_ = input.readInt64();
              break;
            }
            case 64: {
              int rawValue = input.readEnum();
              OperationType value = OperationType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(8, rawValue);
              } else {
                bitField0_ |= 0x00000080;
                operation_ = rawValue;
              }
              break;
            }
            case 74: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000100;
              signature_ = bs;
              break;
            }
            case 82: {
              bitField0_ |= 0x00000200;
              data_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return GatewayProto.internal_static_netty_Transfer_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return GatewayProto.internal_static_netty_Transfer_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Transfer.class, Builder.class);
    }

    private int bitField0_;
    public static final int REQUEST_ID_FIELD_NUMBER = 1;
    private long requestId_;
    /**
     * <code>optional int64 request_id = 1 [default = 0];</code>
     */
    public boolean hasRequestId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int64 request_id = 1 [default = 0];</code>
     */
    public long getRequestId() {
      return requestId_;
    }

    public static final int NODE_ID_FIELD_NUMBER = 2;
    private long nodeId_;
    /**
     * <code>required int64 node_id = 2;</code>
     */
    public boolean hasNodeId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int64 node_id = 2;</code>
     */
    public long getNodeId() {
      return nodeId_;
    }

    public static final int NODE_HOST_FIELD_NUMBER = 3;
    private volatile Object nodeHost_;
    /**
     * <code>required string node_host = 3;</code>
     */
    public boolean hasNodeHost() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string node_host = 3;</code>
     */
    public String getNodeHost() {
      Object ref = nodeHost_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          nodeHost_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string node_host = 3;</code>
     */
    public com.google.protobuf.ByteString
        getNodeHostBytes() {
      Object ref = nodeHost_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        nodeHost_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NODE_PORT_FIELD_NUMBER = 4;
    private int nodePort_;
    /**
     * <code>required int32 node_port = 4;</code>
     */
    public boolean hasNodePort() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int32 node_port = 4;</code>
     */
    public int getNodePort() {
      return nodePort_;
    }

    public static final int SERVICE_NAME_FIELD_NUMBER = 5;
    private volatile Object serviceName_;
    /**
     * <code>optional string service_name = 5;</code>
     */
    public boolean hasServiceName() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string service_name = 5;</code>
     */
    public String getServiceName() {
      Object ref = serviceName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          serviceName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string service_name = 5;</code>
     */
    public com.google.protobuf.ByteString
        getServiceNameBytes() {
      Object ref = serviceName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        serviceName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SERVICE_HOST_FIELD_NUMBER = 6;
    private volatile Object serviceHost_;
    /**
     * <code>optional string service_host = 6;</code>
     */
    public boolean hasServiceHost() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string service_host = 6;</code>
     */
    public String getServiceHost() {
      Object ref = serviceHost_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          serviceHost_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string service_host = 6;</code>
     */
    public com.google.protobuf.ByteString
        getServiceHostBytes() {
      Object ref = serviceHost_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        serviceHost_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SERVICE_ID_FIELD_NUMBER = 7;
    private long serviceId_;
    /**
     * <code>optional int64 service_id = 7;</code>
     */
    public boolean hasServiceId() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional int64 service_id = 7;</code>
     */
    public long getServiceId() {
      return serviceId_;
    }

    public static final int OPERATION_FIELD_NUMBER = 8;
    private int operation_;
    /**
     * <code>required .netty.OperationType operation = 8;</code>
     */
    public boolean hasOperation() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>required .netty.OperationType operation = 8;</code>
     */
    public OperationType getOperation() {
      OperationType result = OperationType.valueOf(operation_);
      return result == null ? OperationType.HEARTBEAT : result;
    }

    public static final int SIGNATURE_FIELD_NUMBER = 9;
    private volatile Object signature_;
    /**
     * <code>optional string signature = 9;</code>
     */
    public boolean hasSignature() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional string signature = 9;</code>
     */
    public String getSignature() {
      Object ref = signature_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          signature_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string signature = 9;</code>
     */
    public com.google.protobuf.ByteString
        getSignatureBytes() {
      Object ref = signature_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        signature_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATA_FIELD_NUMBER = 10;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>optional bytes data = 10;</code>
     */
    public boolean hasData() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>optional bytes data = 10;</code>
     */
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasNodeId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasNodeHost()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasNodePort()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasOperation()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, requestId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, nodeId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, nodeHost_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, nodePort_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, serviceName_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, serviceHost_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt64(7, serviceId_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeEnum(8, operation_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, signature_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeBytes(10, data_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, requestId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, nodeId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, nodeHost_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, nodePort_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, serviceName_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, serviceHost_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(7, serviceId_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(8, operation_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, signature_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(10, data_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Transfer)) {
        return super.equals(obj);
      }
      Transfer other = (Transfer) obj;

      boolean result = true;
      result = result && (hasRequestId() == other.hasRequestId());
      if (hasRequestId()) {
        result = result && (getRequestId()
            == other.getRequestId());
      }
      result = result && (hasNodeId() == other.hasNodeId());
      if (hasNodeId()) {
        result = result && (getNodeId()
            == other.getNodeId());
      }
      result = result && (hasNodeHost() == other.hasNodeHost());
      if (hasNodeHost()) {
        result = result && getNodeHost()
            .equals(other.getNodeHost());
      }
      result = result && (hasNodePort() == other.hasNodePort());
      if (hasNodePort()) {
        result = result && (getNodePort()
            == other.getNodePort());
      }
      result = result && (hasServiceName() == other.hasServiceName());
      if (hasServiceName()) {
        result = result && getServiceName()
            .equals(other.getServiceName());
      }
      result = result && (hasServiceHost() == other.hasServiceHost());
      if (hasServiceHost()) {
        result = result && getServiceHost()
            .equals(other.getServiceHost());
      }
      result = result && (hasServiceId() == other.hasServiceId());
      if (hasServiceId()) {
        result = result && (getServiceId()
            == other.getServiceId());
      }
      result = result && (hasOperation() == other.hasOperation());
      if (hasOperation()) {
        result = result && operation_ == other.operation_;
      }
      result = result && (hasSignature() == other.hasSignature());
      if (hasSignature()) {
        result = result && getSignature()
            .equals(other.getSignature());
      }
      result = result && (hasData() == other.hasData());
      if (hasData()) {
        result = result && getData()
            .equals(other.getData());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasRequestId()) {
        hash = (37 * hash) + REQUEST_ID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getRequestId());
      }
      if (hasNodeId()) {
        hash = (37 * hash) + NODE_ID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getNodeId());
      }
      if (hasNodeHost()) {
        hash = (37 * hash) + NODE_HOST_FIELD_NUMBER;
        hash = (53 * hash) + getNodeHost().hashCode();
      }
      if (hasNodePort()) {
        hash = (37 * hash) + NODE_PORT_FIELD_NUMBER;
        hash = (53 * hash) + getNodePort();
      }
      if (hasServiceName()) {
        hash = (37 * hash) + SERVICE_NAME_FIELD_NUMBER;
        hash = (53 * hash) + getServiceName().hashCode();
      }
      if (hasServiceHost()) {
        hash = (37 * hash) + SERVICE_HOST_FIELD_NUMBER;
        hash = (53 * hash) + getServiceHost().hashCode();
      }
      if (hasServiceId()) {
        hash = (37 * hash) + SERVICE_ID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getServiceId());
      }
      if (hasOperation()) {
        hash = (37 * hash) + OPERATION_FIELD_NUMBER;
        hash = (53 * hash) + operation_;
      }
      if (hasSignature()) {
        hash = (37 * hash) + SIGNATURE_FIELD_NUMBER;
        hash = (53 * hash) + getSignature().hashCode();
      }
      if (hasData()) {
        hash = (37 * hash) + DATA_FIELD_NUMBER;
        hash = (53 * hash) + getData().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Transfer parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Transfer parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Transfer parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Transfer parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Transfer parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Transfer parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Transfer parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Transfer parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Transfer parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Transfer parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Transfer parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Transfer parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Transfer prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code netty.Transfer}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:netty.Transfer)
        TransferOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return GatewayProto.internal_static_netty_Transfer_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return GatewayProto.internal_static_netty_Transfer_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Transfer.class, Builder.class);
      }

      // Construct using com.pandong.tool.gateway.common.model.GatewayProto.Transfer.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        requestId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        nodeId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        nodeHost_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        nodePort_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        serviceName_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        serviceHost_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        serviceId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000040);
        operation_ = 0;
        bitField0_ = (bitField0_ & ~0x00000080);
        signature_ = "";
        bitField0_ = (bitField0_ & ~0x00000100);
        data_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000200);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return GatewayProto.internal_static_netty_Transfer_descriptor;
      }

      public Transfer getDefaultInstanceForType() {
        return Transfer.getDefaultInstance();
      }

      public Transfer build() {
        Transfer result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Transfer buildPartial() {
        Transfer result = new Transfer(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.requestId_ = requestId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.nodeId_ = nodeId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.nodeHost_ = nodeHost_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.nodePort_ = nodePort_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.serviceName_ = serviceName_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.serviceHost_ = serviceHost_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.serviceId_ = serviceId_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.operation_ = operation_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.signature_ = signature_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.data_ = data_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Transfer) {
          return mergeFrom((Transfer)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Transfer other) {
        if (other == Transfer.getDefaultInstance()) return this;
        if (other.hasRequestId()) {
          setRequestId(other.getRequestId());
        }
        if (other.hasNodeId()) {
          setNodeId(other.getNodeId());
        }
        if (other.hasNodeHost()) {
          bitField0_ |= 0x00000004;
          nodeHost_ = other.nodeHost_;
          onChanged();
        }
        if (other.hasNodePort()) {
          setNodePort(other.getNodePort());
        }
        if (other.hasServiceName()) {
          bitField0_ |= 0x00000010;
          serviceName_ = other.serviceName_;
          onChanged();
        }
        if (other.hasServiceHost()) {
          bitField0_ |= 0x00000020;
          serviceHost_ = other.serviceHost_;
          onChanged();
        }
        if (other.hasServiceId()) {
          setServiceId(other.getServiceId());
        }
        if (other.hasOperation()) {
          setOperation(other.getOperation());
        }
        if (other.hasSignature()) {
          bitField0_ |= 0x00000100;
          signature_ = other.signature_;
          onChanged();
        }
        if (other.hasData()) {
          setData(other.getData());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasNodeId()) {
          return false;
        }
        if (!hasNodeHost()) {
          return false;
        }
        if (!hasNodePort()) {
          return false;
        }
        if (!hasOperation()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Transfer parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Transfer) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long requestId_ ;
      /**
       * <code>optional int64 request_id = 1 [default = 0];</code>
       */
      public boolean hasRequestId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int64 request_id = 1 [default = 0];</code>
       */
      public long getRequestId() {
        return requestId_;
      }
      /**
       * <code>optional int64 request_id = 1 [default = 0];</code>
       */
      public Builder setRequestId(long value) {
        bitField0_ |= 0x00000001;
        requestId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 request_id = 1 [default = 0];</code>
       */
      public Builder clearRequestId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        requestId_ = 0L;
        onChanged();
        return this;
      }

      private long nodeId_ ;
      /**
       * <code>required int64 node_id = 2;</code>
       */
      public boolean hasNodeId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int64 node_id = 2;</code>
       */
      public long getNodeId() {
        return nodeId_;
      }
      /**
       * <code>required int64 node_id = 2;</code>
       */
      public Builder setNodeId(long value) {
        bitField0_ |= 0x00000002;
        nodeId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 node_id = 2;</code>
       */
      public Builder clearNodeId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        nodeId_ = 0L;
        onChanged();
        return this;
      }

      private Object nodeHost_ = "";
      /**
       * <code>required string node_host = 3;</code>
       */
      public boolean hasNodeHost() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string node_host = 3;</code>
       */
      public String getNodeHost() {
        Object ref = nodeHost_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            nodeHost_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string node_host = 3;</code>
       */
      public com.google.protobuf.ByteString
          getNodeHostBytes() {
        Object ref = nodeHost_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          nodeHost_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string node_host = 3;</code>
       */
      public Builder setNodeHost(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        nodeHost_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string node_host = 3;</code>
       */
      public Builder clearNodeHost() {
        bitField0_ = (bitField0_ & ~0x00000004);
        nodeHost_ = getDefaultInstance().getNodeHost();
        onChanged();
        return this;
      }
      /**
       * <code>required string node_host = 3;</code>
       */
      public Builder setNodeHostBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        nodeHost_ = value;
        onChanged();
        return this;
      }

      private int nodePort_ ;
      /**
       * <code>required int32 node_port = 4;</code>
       */
      public boolean hasNodePort() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int32 node_port = 4;</code>
       */
      public int getNodePort() {
        return nodePort_;
      }
      /**
       * <code>required int32 node_port = 4;</code>
       */
      public Builder setNodePort(int value) {
        bitField0_ |= 0x00000008;
        nodePort_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 node_port = 4;</code>
       */
      public Builder clearNodePort() {
        bitField0_ = (bitField0_ & ~0x00000008);
        nodePort_ = 0;
        onChanged();
        return this;
      }

      private Object serviceName_ = "";
      /**
       * <code>optional string service_name = 5;</code>
       */
      public boolean hasServiceName() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string service_name = 5;</code>
       */
      public String getServiceName() {
        Object ref = serviceName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            serviceName_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string service_name = 5;</code>
       */
      public com.google.protobuf.ByteString
          getServiceNameBytes() {
        Object ref = serviceName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          serviceName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string service_name = 5;</code>
       */
      public Builder setServiceName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        serviceName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string service_name = 5;</code>
       */
      public Builder clearServiceName() {
        bitField0_ = (bitField0_ & ~0x00000010);
        serviceName_ = getDefaultInstance().getServiceName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string service_name = 5;</code>
       */
      public Builder setServiceNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        serviceName_ = value;
        onChanged();
        return this;
      }

      private Object serviceHost_ = "";
      /**
       * <code>optional string service_host = 6;</code>
       */
      public boolean hasServiceHost() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional string service_host = 6;</code>
       */
      public String getServiceHost() {
        Object ref = serviceHost_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            serviceHost_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string service_host = 6;</code>
       */
      public com.google.protobuf.ByteString
          getServiceHostBytes() {
        Object ref = serviceHost_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          serviceHost_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string service_host = 6;</code>
       */
      public Builder setServiceHost(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        serviceHost_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string service_host = 6;</code>
       */
      public Builder clearServiceHost() {
        bitField0_ = (bitField0_ & ~0x00000020);
        serviceHost_ = getDefaultInstance().getServiceHost();
        onChanged();
        return this;
      }
      /**
       * <code>optional string service_host = 6;</code>
       */
      public Builder setServiceHostBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        serviceHost_ = value;
        onChanged();
        return this;
      }

      private long serviceId_ ;
      /**
       * <code>optional int64 service_id = 7;</code>
       */
      public boolean hasServiceId() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional int64 service_id = 7;</code>
       */
      public long getServiceId() {
        return serviceId_;
      }
      /**
       * <code>optional int64 service_id = 7;</code>
       */
      public Builder setServiceId(long value) {
        bitField0_ |= 0x00000040;
        serviceId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 service_id = 7;</code>
       */
      public Builder clearServiceId() {
        bitField0_ = (bitField0_ & ~0x00000040);
        serviceId_ = 0L;
        onChanged();
        return this;
      }

      private int operation_ = 0;
      /**
       * <code>required .netty.OperationType operation = 8;</code>
       */
      public boolean hasOperation() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>required .netty.OperationType operation = 8;</code>
       */
      public OperationType getOperation() {
        OperationType result = OperationType.valueOf(operation_);
        return result == null ? OperationType.HEARTBEAT : result;
      }
      /**
       * <code>required .netty.OperationType operation = 8;</code>
       */
      public Builder setOperation(OperationType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000080;
        operation_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>required .netty.OperationType operation = 8;</code>
       */
      public Builder clearOperation() {
        bitField0_ = (bitField0_ & ~0x00000080);
        operation_ = 0;
        onChanged();
        return this;
      }

      private Object signature_ = "";
      /**
       * <code>optional string signature = 9;</code>
       */
      public boolean hasSignature() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional string signature = 9;</code>
       */
      public String getSignature() {
        Object ref = signature_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            signature_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string signature = 9;</code>
       */
      public com.google.protobuf.ByteString
          getSignatureBytes() {
        Object ref = signature_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          signature_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string signature = 9;</code>
       */
      public Builder setSignature(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        signature_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string signature = 9;</code>
       */
      public Builder clearSignature() {
        bitField0_ = (bitField0_ & ~0x00000100);
        signature_ = getDefaultInstance().getSignature();
        onChanged();
        return this;
      }
      /**
       * <code>optional string signature = 9;</code>
       */
      public Builder setSignatureBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        signature_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes data = 10;</code>
       */
      public boolean hasData() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>optional bytes data = 10;</code>
       */
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>optional bytes data = 10;</code>
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes data = 10;</code>
       */
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000200);
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:netty.Transfer)
    }

    // @@protoc_insertion_point(class_scope:netty.Transfer)
    private static final Transfer DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Transfer();
    }

    public static Transfer getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<Transfer>
        PARSER = new com.google.protobuf.AbstractParser<Transfer>() {
      public Transfer parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Transfer(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Transfer> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Transfer> getParserForType() {
      return PARSER;
    }

    public Transfer getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_netty_Transfer_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_netty_Transfer_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\024MessagePackage.proto\022\005netty\"\342\001\n\010Transf" +
      "er\022\025\n\nrequest_id\030\001 \001(\003:\0010\022\017\n\007node_id\030\002 \002" +
      "(\003\022\021\n\tnode_host\030\003 \002(\t\022\021\n\tnode_port\030\004 \002(\005" +
      "\022\024\n\014service_name\030\005 \001(\t\022\024\n\014service_host\030\006" +
      " \001(\t\022\022\n\nservice_id\030\007 \001(\003\022\'\n\toperation\030\010 " +
      "\002(\0162\024.netty.OperationType\022\021\n\tsignature\030\t" +
      " \001(\t\022\014\n\004data\030\n \001(\014*,\n\rOperationType\022\r\n\tH" +
      "EARTBEAT\020\000\022\014\n\010REGISTER\020\001B5\n%com.pandong." +
      "tool.gateway.common.modelB\014GatewayProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_netty_Transfer_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_netty_Transfer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_netty_Transfer_descriptor,
        new String[] { "RequestId", "NodeId", "NodeHost", "NodePort", "ServiceName", "ServiceHost", "ServiceId", "Operation", "Signature", "Data", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
